In [21]:
import numpy as np

a = np.array([2,3,4,5], int)
b = np.array([[2,4,6,8], [1,3,5,7]], int)

print(a[0])

print(a[2:])

print(a[:4])

print(b[1,1])

print(b[0,:]) #print [2 4 6 8]

print(b.shape) 

print(b.dtype)

print(len(b))

print(7 in b)

2
[4 5]
[2 3 4 5]
3
[2 4 6 8]
(2, 4)
int32
2
True


In [27]:
import numpy as np

a = np.array(range(12), int)
print(a)
print(a.shape)

#NOTE: reshape does not change the original array. It creates a new array with the new shape
a = a.reshape((4,3))
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [35]:
import numpy as np

a = np.array(range(12), int)
print(a)


b = a.copy()
c = b.tolist()

b.fill(0)
print(b)

d = a[:, np.newaxis]
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 0 0 0 0 0 0 0 0 0 0 0]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [38]:
import numpy as np

a = np.zeros((4,3), int)
print(a)

b = np.ones((5,5), float)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [41]:
import numpy as np

a = np.array([True, False, False], bool)

#To find any a is True
print(any(a))

#To firnd all a is True
print(all(a))

b = np.array([1,3,5,6,8,2,9], int)
print(np.logical_and(b >2 , b<9))



True
False
[False  True  True  True  True False False]
